### ISSUE TITLE
Generate a shasum for packages to prevent attacks

### ISSUE THREAD

**Issue by tmoitie** [blazersix/satispress#1]

**Comment by bradyvercher** [comment]
Hi @tmoitie! I'm not entirely familiar with how Composer handles the shasum property, but let me know how that change works out for you.

**Comment by tmoitie** [comment]
Looks about right from the commit. Composer will shasum the archive upon download and compare with the one in the packages.json. If there's a difference it will halt the action and alert the user to a potential MITM attack.
