### ISSUE TITLE
TransportException

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#10]
> [Composer\Downloader\TransportException]  
> "https://satis.example.com/satispress/my-plugin/1.0.0" appears broken, and returned an empty 200 response

While visiting the URL directly correctly downloads a zip file, Composer throws this error.

Any suggestions?

**Comment by bradyvercher** [comment]
The only time I ran into something similar was in relation to #6. You migh check your error log on the package server and try downloading the file using cURL in your terminal to see if errors out.

**Comment by bradyvercher** [comment]
There haven't been any additional reports related to this issue, so I'm closing it out. Feel free to reopen if this is still an issue.
