### ISSUE TITLE
Add option for enabling auto updates of plugins and themes

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#12]
Suggestion: Add a checkbox which allows the following to be triggered, which in turn enables automatic updates of plugins and themes:

```
add_filter( 'auto_update_plugin', '__return_true' );
add_filter( 'auto_update_theme', '__return_true' );
```

The benefit is then that the SatisPress site doesn't need to be checked regularly and have plugins and themes manually updated. While these two lines could be added to any other plugin or theme installed on the site, I think it makes sense in this case to make it a part of SatisPress.

**Comment by bradyvercher** [comment]
There's a note in the readme that suggests [Update Control](https://wordpress.org/plugins/update-control/) for that purpose. Is there any reason that won't work?

**Comment by GaryJones** [comment]
No, that should work fine then :-)
