### ISSUE TITLE
Release list improvements

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#14]
Currently, the release list for a package looks like this:

![Current SatisPress release list](https://cloud.githubusercontent.com/assets/88371/21007433/b36cebec-bd34-11e6-9abe-ece981de6795.png)

Improvements that could be done:

* Commas between release numbers
* Inconsistent ordering fixed, with newest release first (and maybe made bold?)

![Mockup of improved release list](https://cloud.githubusercontent.com/assets/88371/21007673/cf5791a8-bd35-11e6-96be-96d321d318a8.png)

**Comment by GaryJones** [comment]
If #17 is completed, then [this static function](https://github.com/composer/semver/blob/0bdf393dbafaebf79a8517140f661cedf40e36a4/src/Semver.php#L69) can be used to do the sorting.

**Comment by bradyvercher** [comment]
This looks like it's already been taken care of.
