### ISSUE TITLE
Add Github Updater Headers

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#16]
Right now, there's no way to get automatic updates. We either need to add GitHub Updater headers to the plugin, or consider adding it to the wp.org repo to support standard updating.

@bradyvercher What would be your preference?

**Comment by bradyvercher** [comment]
Probably the header for GitHub Updater at this point. I've just been doing a `git pull` on the server where I run this and I'm not sure how much use it actually receives.

**Comment by GaryJones** [comment]
It got mentioned in a WordPress London meetup by a speaker, so it definitely has its fans!

**Comment by bradyvercher** [comment]
Interesting! I've been considering finishing up a sort of successor to SatisPress that improves on a lot of the concepts here and releasing it next year, but I'm still trying to gauge interest in something like that.
