### ISSUE TITLE
Use composer/semver package

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#17]
Since the VersionParser has now been extracted out of Composer and into it's own [repo](https://github.com/composer/semver), we should consider pulling in [`composer/semver`](https://packagist.org/packages/composer/semver) as a dependency, instead of having a manual copy.

* [ ] Check what our current [SatisPress_Version_Parser](https://github.com/blazersix/satispress/blob/37db219fad3619184e7673a05b2e5b0ed57c3f6c/includes/class-satispress-version-parser.php) does that might be intentionally different to the [upstream class](https://github.com/composer/semver/blob/0bdf393dbafaebf79a8517140f661cedf40e36a4/src/VersionParser.php).

**Comment by bradyvercher** [comment]
Aside from formatting changes and removing some unneeded code, there shouldn't be any functional differences. The plugin currently stands on its own and can be installed directly from GitHub without a build process, so if we only need a method or two for sorting releases, I'd rather copy those over for now.

**Comment by GaryJones** [comment]
In terms of sorting, the `Semver::usort()` method needs `Comparator::lessThan()`, which needs `Comparator::compare()`, which needs a `Constraint` class, which implements the `ConstraintInterface` and so on. It really would just make more sense to include the package, and commit the vendor directory so that there was no build process.

Alternatively, GitHub Updater supports there being a [Release Asset](https://github.com/afragen/github-updater/wiki/Settings#release-assets) so when a new release is made, build locally, upload a zip to GitHub attached to the tagged Release, and updates will work.

**Comment by bradyvercher** [comment]
My main concern with committing dependencies is that it creates the potential for conflict if other plugins do the same with a different version. In this case, it's probably not likely, but still a possibility.

There are tradeoffs for every approach, but I guess if we're going to do it, might as well go all in and use the release assets and we can add a script to handle packaging if necessary.
