### ISSUE TITLE
@todo: get_packages_json(): Consider caching to a static file instead.

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#19]
Moving the `@todo` here:

https://github.com/blazersix/satispress/blob/8a68344c973fb159d4f310badfd4c18ec70aeef9/includes/class-satispress.php#L131

**Comment by bradyvercher** [comment]
This hasn't been necessary to this point, so I'm going to go ahead and close it out.

**Comment by AaronHolbrook** [comment]
Loading the packages.json file takes upwards of 5 seconds.

Doesn't seem like much until you consider this is just one of 3 different repositories that our agency uses in our composer files. And running composer update/install is then slowed down by this extra 5 seconds, it starts to add up.

I would love to see this re-opened and optimizing the load off the request. Would you be up for a PR?

**Comment by bradyvercher** [comment]
This particular issue is related to a comment in an older version -- go ahead and open a new issue for discussion. I figured it would be necessary, but didn't want to optimize too early.

**Comment by rfair404** [comment]
I'm wondering if this is related to why I'm getting "internal server error" when having a large number of plugins.

**Comment by bradyvercher** [comment]
@rfair404 This is related to an older version of the plugin. If you're having an internal server issue that you think is related to SatisPress, please open a new issue with details about where you're receiving the error and any relevant log messages.
