### ISSUE TITLE
Can't disable HTTP Basic Auth

### ISSUE THREAD

**Issue by emzo** [blazersix/satispress#2]
Hi Brady. Huge thanks for this - very useful!

Regarding the setting to enable/disable HTTP Basic Auth, I noticed that although this setting does indeed modify the .htaccess file within /wp-content/uploads/satispress/ thereby denying direct access to package archives files such as https://example.com/wp-content/uploads/satispress/my-package/my-package-1.0.0.zip, it doesn't disable Authentication altogether.

Attempting to access a package at the URL provided by the SatisPress packages.json file (such as https://example.com/satispress/my-package/1.0.0) still brings up a login prompt.

Is this expected behaviour? I would expect unchecking the 'Enable HTTP Basic Authentication?' option should disable authentication altogether. If you agree, I can try and send a PR to fix?

**Comment by bradyvercher** [comment]
Thanks @emzo, glad you found it useful!

That's not the expected behavior, so if it is indeed a bug, a PR would be highly appreciated.

**Comment by bradyvercher** [comment]
Thanks for the fix @emzo! I went ahead and tagged v0.2.1 with this a couple of other minor changes.
