### ISSUE TITLE
SatisPress Package interface

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#21]
The `SatisPress_Package` is extended by `SatisPress_Package_Plugin` and `SatisPress_Package_Theme`. Some methods exist in both child classes, with some being class-specific, and some being identical.

Elsewhere in the code, arrays of `$packages` are correctly treated without caring what type of package they are. Methods are called against them. This existence of polymorphism strongly suggests that an interface should exist, so it can be type-hinted against.

What I'd like to see:

* `SatisPress_Package` being marked as abstract.
* `SatisPress_Package` implementing a new interface which lists all the methods common between plugin and theme classes and in the abstract base class.
* Updating the autoloader so that we don't have an interface in a file prefixed with `class-`.
* Move identical methods, like `get_slug()` into the base class.
* More consistency between the two classes regarding reading package data i.e. the them class grabs it once during the class constructor, while the plugin class lazily grabs it via a protected method.
* Values returned from `get_type()` methods moved to class constants, so that the method to retrieve it can be refactored to return that constant, and can therefore be moved into the base class.

**Comment by bradyvercher** [comment]
If I were writing this today, I'd definitely do a lot different. This sounds like a good start, although the autoloader can probably be removed after #17.

**Comment by GaryJones** [comment]
## Done

- [SatisPress\Package](https://github.com/blazersix/satispress/blob/9155f76485d01849c0a2798f34b1d4ba28d77bfc/src/Package.php) is now an abstract class, which the [PackageType classes](https://github.com/blazersix/satispress/tree/develop/src/PackageType) extend.
- No interface, but the common methods are [included] as abstract methods.
- The [autoloader](https://github.com/blazersix/satispress/blob/9155f76485d01849c0a2798f34b1d4ba28d77bfc/satispress.php#L63-L88) and file naming is now PSR-4 compliant.

## Outstanding
- Left `get_slug()` where it is for now.
- Approaches between the two for grabbing data are still different
- Wasn't sure on this one - not keen on having a base class method rely on the presence of a child class constant. Needs more 🤔.

**Comment by bradyvercher** [comment]
This should be good to go now that #52 has landed.
