### ISSUE TITLE
Package.json not being created

### ISSUE THREAD

**Issue by zamson** [blazersix/satispress#23]
First of all thanks for this amazing plugin. It has help out a lot with projects the past year. Recently tried to move/create a new repo on a server running PHP 7.0.x. 

However the package.json transient does not get created thus rendering a 404. Any ideas?

![image](https://cloud.githubusercontent.com/assets/11811478/22783251/446b6aac-eecb-11e6-86db-ab5b1ad81dba.png)

![image](https://cloud.githubusercontent.com/assets/11811478/22783315/8953747a-eecb-11e6-9d4c-327f5dc64f92.png)

**Comment by GaryJones** [comment]
I don't think this will be a PHP 7 issue, as I have it running just fine on my PHP 7 install.

What version / commit of SatisPress are you running?

**Comment by GaryJones** [comment]
Ah, the [last commit in the `develop` branch](https://github.com/blazersix/satispress/commit/b792d29529a8f5036822c1a94f392a646aabb8aa) might be the solution to your issue - let me know if it is!

If so, then we can look at getting this merged to `master`, tagged and released.

**Comment by zamson** [comment]
Thanks for getting back to me.

Not sure if that was the culprit. Downloaded and applied the develop branch instead of latest release. Also installed the Nginx helper plugin and all of a sudden it started working. Could be related to cache or nginx rewrites. Not sure atm but now it's working!

**Comment by GaryJones** [comment]
I'll close as a duplicate then.
