### ISSUE TITLE
Error in plugin when version number of plugin has more than 3 digits

### ISSUE THREAD

**Issue by Mark-Creeten** [blazersix/satispress#28]
I noticed that when i update a plugin that is controlled by Satispress, and the version numbering of that plugin is moren than (normal), Satispress trows an error & all plugins are not visible anymore & package.json is not available.

<img width="775" alt="screen shot 2017-11-17 at 11 49 39" src="https://user-images.githubusercontent.com/1265148/32943853-d3897b9e-cb8d-11e7-8510-1e93d1ea2d6a.png">

**Comment by GaryJones** [comment]
@Mark-Creeten Possibly related to #13 (but perhaps you have error reporting turned off)?

**Comment by Mark-Creeten** [comment]
@GaryJones indeed, looks related, i get the same error message.

**Comment by GaryJones** [comment]
Duplicate of #13.
