### ISSUE TITLE
Package.json, satispress_packages_json transient and SatisPress Repository URL not found

### ISSUE THREAD

**Issue by Raruto** [blazersix/satispress#29]
Hello all,
I'm trying to set up a simple wordpress site (localhost) so that it is under the git version control system (in a KISS way, ie without having to save all wordpress installation folder).
I have recently discovered that a similar result can be achieved through the use of [composer](https://getcomposer.org/) and [wpackagist](https://wpackagist.org/) (eg [here](https://medium.com/@halles/wordpress-composer-git-1ccf29a9827a) is a random guide from the internet).

Digging into the internet I found your repo, if I understand correctly, it allows me to generate a "composer.json" file directly from the list of installed plugins / themes? (reusable in other installations?)
It would be interesting if it were possible to change the base URL domain from `"http://localhost/"` to `"https://wpackagist.org/"` (or any custom one)

Leaving aside any digression..

Like the issue https://github.com/blazersix/satispress/issues/23:
![satispress_ _chesssifa_ _wordpress](https://user-images.githubusercontent.com/9614886/38204293-a20b5c9c-36a2-11e8-859a-1e72b532dc22.png)
- if click on the **SatisPress Repository URL** i've got a 404 error page (even after permalink refresh) 
- i've even searched the **Package.json**, with no luck, into the wordpress installation folder
- [transients-manager](https://wordpress.org/plugins/transients-manager/) doesn't reveal any **satispress_packages_json** transient (even after delete all transients)

My current system is: **WP 4.9.4**, **PHP 7.0.9** and **Satipress 0.2.3**

Any way, thanks for the effort!

**Comment by bradyvercher** [comment]
Hi @Raruto, SatisPress allows you to create a Composer repository of installed plugins and themes that you can reference in your project's `composer.json.` It doesn't create the `composer.json` for your project. You might take a look at [Composerpress](https://github.com/tomjn/composerpress) if you need that functionality.

I can't say for sure why you're seeing a 404 when visiting the repository URL, but I have seen some server configurations that don't route URLs with a file extension for normally static files through WordPress, which may be the case here. You can try accessing the repository at http://localhost/wordpress/?satispress=packages.json to see if that works.

**Comment by Raruto** [comment]
Oh man, thanks for your time saver tip! I'll definitely take a look at it later..

Reading [this](http://blog.servergrove.com/2015/04/29/satis-building-composer-repository/) article I realized that Satis is used (also?) as own "reverse-proxy repo" of [Packagist](http://packagist.org/).

If I can, I would suggest you to add a few more lines in the readme.md file about [Satis](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#satis) (or just some links)

> You can try accessing the repository at http://localhost/wordpress/?satispress=packages.json to see if that works.

Yup, it works!

![localhost_wordpress_satispress packages json](https://user-images.githubusercontent.com/9614886/38273156-88d26c9a-378b-11e8-9ca2-ae88048db63d.png)

>I can't say for sure why you're seeing a 404 when visiting the repository URL, but I have seen some server configurations that don't route URLs with a file extension for normally static files through WordPress, which may be the case here.

### Some Query Monitor Info:
**Rewrite Rules**
![QM 404 page](https://user-images.githubusercontent.com/9614886/38272910-ef3138fa-378a-11e8-91ad-0307a9092ea8.png)
**Enviroment**
![QM 404 page](https://user-images.githubusercontent.com/9614886/38273374-090d77c4-378c-11e8-92ce-8c72083431b7.png)
**MAMP** v3.2.2.25955

if it helps, I can also provide other information...

**Comment by GaryJones** [comment]
> add a few more lines in the readme.md file about Satis

Opened #31 to handle this :-) Thanks for the idea.

To summarise the main issue:
 - http://localhost/wordpress/?satispress=packages.json works
 - http://localhost/wordpress/satispress/packages.json (linked from the SatisPress settings page) doesn't work (404), even after permalink refresh.

Correct?

I've just done a big refactor on to the `develop` branch. I don't think there was anything related to the issue you were having, but could you please try, before we spend any more time looking into this?

**Comment by Raruto** [comment]
Hi Gary,
It's been a while since I did the test on the local server (which obviously changed with time..), by the way, the only "big difference" that I notice compared to what i had before are:
- WP version is 4.9.5 (and not 4.9.4) 
- I no longer had the plugin installed (so I've re-installed the version 0.2.3)
- (after plugin's activation) I did not perform any permalink refresh
- now both links work properly
- and now exists a satispress_packages_json transient..

seeing it now would seem a trivial problem related to caching (although I tend to try to be very careful...)

**Comment by GaryJones** [comment]
@Raruto Thanks for taking the time to test. I'm hearing that since both links now work properly, the issue can be closed.
