### ISSUE TITLE
Download URL to get latest version

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#36]
See https://github.com/TGMPA/TGM-Plugin-Activation/issues/746#issuecomment-401278304

We currently support URLs like `https://example.com/satispress/gravityforms/2.3.1`, but this would require a URL like `https://example.com/satispress/gravityforms/latest` that would automagically resolve to the highest version. No other constraint-resolution would be needed.

**Comment by bradyvercher** [comment]
This should be good to go with #38.
