### ISSUE TITLE
Consider Decorator pattern

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#39]
See https://github.com/blazersix/satispress/pull/35#discussion_r198749710

**Comment by bradyvercher** [comment]
That caching is kind of a pain for development and I keep thinking it should go in a different layer (maybe leave it up to the server?), but running those checksums for every request could get expensive.

For the time being, I'm running this filter during development: `add_filter( 'pre_transient_satispress_packages', '__return_null' );`

**Comment by GaryJones** [comment]
Could (should) that workaround be automatically applied inside a `WP_DEBUG` check?

**Comment by bradyvercher** [comment]
That could work, but I'm working on refactoring the package handling right now that should make it easier to implement different caching strategies in places like this. If it doesn't work out like I'm hoping, then we can add that filter in somewhere. 🤞

**Comment by bradyvercher** [comment]
I'm going to go ahead and leave the caching out for now and we'll see if it needs to be added back in the future.

After #58, it should be fairly easy to write a decorator to implement custom caching implementations. They just need to take into consideration that the output could change from user to user.
