### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by widoz** [blazersix/satispress#42]
`
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/guido/Sites/dev_wp/wp-content/plugins/satispress/src/Storage/Local.php on line 104
`
Within the plugins SatisPress table column

`DirectoryIterator` doesn't implement `Countable` interface, for this case use `iterator_count`

**Comment by bradyvercher** [comment]
Fixed in #43
