### ISSUE TITLE
All plugins downloaded within the plugin dir despite configuration on local installation

### ISSUE THREAD

**Issue by widoz** [blazersix/satispress#45]
Despite the flags set for plugins when I add the repository to my `composer.json` file I get all of the plugins runnig `composer install` within the directory `wp-content/plugins/hello`.

In my in installation I have gutenberg, hello dolly, user-switching and satispress. 
I selected only hello dolly as satipress plugin and I correctly have it in my `packages.json`

``` 
{"packages":{"satispress\/hello":{"1.7":{"name":"satispress\/hello","version":"1.7","version_normalized":"1.7.0.0","dist":{"type":"zip","url":"http:\/\/localhost\/dev_wp\/satispress\/hello\/1.7","shasum":"7d250c9c966d9f19af8bd1aa1dc34989a373e28d"},"require":{"composer\/installers":"^1.0"},"type":"wordpress-plugin","authors":{"name":"Matt Mullenweg","homepage":"http:\/\/ma.tt\/"},"description":"This is not just a plugin, it symbolizes the hope and enthusiasm of an entire generation summed up in two words sung most famously by Louis Armstrong: Hello, Dolly. When activated you will randomly see a lyric from <cite>Hello, Dolly<\/cite> in the upper right of your admin screen on every page.","homepage":"http:\/\/wordpress.org\/plugins\/hello-dolly\/"}}}}
```

Then in my `composer.json` I have:

```
{
    "name": "guido/testing",
    "repositories": [
        {
            "type": "composer",
            "url": "http://localhost/dev_wp/satispress/packages.json"
        }
    ],
    "require": {
        "satispress\/hello": "1.7"
    },
    "config": {
        "secure-http": false
    }
}
```

Composer install output is:

```
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.5.0): Loading from cache
  - Installing satispress/hello (1.7): Downloading (100%)
```

That seems correctly but navigating to `wp-content/plugins/hello` directory I see all of the plugins I have installed in my `dev_wp` site.

I guess a misconfiguration on my composer.json file.

**Comment by bradyvercher** [comment]
It sounds like your entire plugins directory was included when caching Hello Dolly. If you look in the zip file in the `/wp-content/uploads/satispress-xxx/hello-dolly/` directory, does it include all of your plugins?

Also, is Hello Dolly a single-file plugin or is it in a subdirectory? I think single-file plugins might need to be excluded or at least added to a directory when caching them.

**Comment by widoz** [comment]
> It sounds like your entire plugins directory was included when caching Hello Dolly. If you look in the zip file in the /wp-content/uploads/satispress-xxx/hello-dolly/ directory, does it include all of your plugins?

Yes, also in the .zip downloaded directly by the url `"http://localhost/dev_wp/satispress/hello/1.7"` 

> Also, is Hello Dolly a single-file plugin or is it in a subdirectory?
Single file plugin directly within the `wp-content/plugins` yes.

> I think single-file plugins might need to be excluded or at least added to a directory when caching them.
Yup. If I select only gutenberg for example I do not get that issue.

**Comment by bradyvercher** [comment]
I think ad917b6 should take care of this. You'll probably need to delete the existing zip file in your uploads directory and then remove/add Hello Dolly to the whitelist to regenerate the artifact.

Let me know if you still have issues, though.
