### ISSUE TITLE
Basic http authentication over ssl

### ISSUE THREAD

**Issue by IanEdington** [blazersix/satispress#5]
Hey @blazersix,

This is awesome! Thank you very much for this plugin!

I'm having some problems with my setup though. When I have HTTP Basic Authentication on I'm not able to update my plugins. I have been using the administrators Username and Password but it won't work. If I'm signed into wordpress in a browser it will download but if I open a new window it won't let me in.

Any thoughts?

Thank you,
Ian

**Comment by bradyvercher** [comment]
Hey @IanEdington, I'm not sure I understand the problem. If you're logged into WordPress in a browser, then the standard cookies are used to authenticate requests. Otherwise, if you're not logged in, your browser or client should prompt you to enter your credentials. Are you not receiving the Basic Auth prompt?

**Comment by IanEdington** [comment]
Hey @bradyvercher. Thanks for helping. Here's what happening. I hook up my repo, I reference by private plugin and I run `composer update`. The bouncer asks for my username and password so I oblige, and he says 'Sorry man you're just not cool enough to join this party.'

I tried going back to php5.6 instead of php7
I tried using an alpha numeric password
I'm not getting any error logs

Any thoughts?

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing satispress/sfwd-lms (2.1.8.1)
    Authentication required (test.eyecarepd.com):
      Username: user
      Password: password
    Downloading: Connecting...
  [Composer\Downloader\TransportException]
  Invalid credentials for 'https://test.eyecarepd.com/satispress/sfwd-lms/2.1.8.1', aborting.
```

**Comment by bradyvercher** [comment]
If the username and password are correct, I'm not really sure what the issue might be. You can try deactivating any other plugins and flush your permalinks to make sure there aren't any conflicts.

[This is probably where you'd want to focus](https://github.com/blazersix/satispress/blob/29692e808a22de079214d3f93df1fd81361128b4/includes/class-satispress-authentication-basic.php#L51-L53) if you want to try debugging to make sure the username and password are being set correctly and authentication is working.

**Comment by IanEdington** [comment]
Great thanks for the advice. For now, I've limited access to the host instead of authenticating.

**Comment by GaryJones** [comment]
@IanEdington Are your curl and openssl versions in your compiled PHP, up to date? I wonder if the credentials error message might be misleading here.

**Comment by GaryJones** [comment]
Closing due to lack of feedback.
