### ISSUE TITLE
Rename satispress to satispress-xxx throws a warning

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#50]
On first login after updating to the latest code, I get a PHP Warning:

> Warning: rename(/app/public/wp-content/uploads/satispress,/app/public/wp-content/uploads/satispress-lAUb9bjyV0ND/): Directory not empty in /app/public/wp-content/plugins/satispress/src/Provider/Upgrade.php on line 

(and then it seems I unfortunately didn't manage to copy the line number before refreshing, but I presume its the line with the `rename()` call!)

Both the original and the new directories exist, and both seem to have the plugin directories inside them. After refreshing the admin page, the warning disappears.

**Comment by bradyvercher** [comment]
So it looks like `Upgrade::cache_packages()` was running before the `rename()` call, which created the new cache directory and filled it with the current version of whitelisted packages.

If you were running this on an existing installation with a bunch of cached releases that you need to keep, you'll need to do a couple of things:

1. Update to 2d6d6fe or later
2. Confirm the original `/satispress` cache directory still exists with all the old releases
3. Confirm the new `/satispress-xxxx` cache directory only contains current versions or pending updates
4. If both of those are true, then delete the `/satispress-xxxx` directory
5. Then delete the `satispress_version` option

The next time the admin panel is loaded, the original cache directory should be properly renamed.

**Comment by GaryJones** [comment]
Instructions worked perfectly, thank you :-)
