### ISSUE TITLE
Packages View improvement

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#54]
- [x] Add some text when no packages are exposed, so it's not just an empty screen. Could consider including a link to /docs or GitHub Pages explained how to whitelist a plugin or theme.
- [x] Add `<code>...</code>` around the _Package type_ value.
- [x] Add `target="_blank" rel="noopener noreferer"` to Home Page and Author links.
- [ ] Include a field / link for `/latest` to make it easy to grab the URL / see what version is considered to be / mapped to the latest.

**Comment by bradyvercher** [comment]
This should be good to go after ba2e2b0. The latest version is prepended to the list of versions with a `Latest` button and the download URL uses the `/latest` endpoint for the package.
