### ISSUE TITLE
API Key names are not unique

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#61]
![screenshot 2018-07-10 09 53 19](https://user-images.githubusercontent.com/88371/42499617-22941256-8427-11e8-9686-e9a750062329.png)

I think the name should be validated to be unique, or otherwise follow what slugs do, and have an automatic `-2`, `-3` etc. appended.

**Comment by bradyvercher** [comment]
The name is just a human-friendly description for the API Key and there's not really a technical need to make it unique. If someone creates one with a duplicate name, they can delete it and generate a new one, or the name could be made editable in the future.

Let me know if I'm missing something, though.
