### ISSUE TITLE
Consider introducing logging

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#63]
An administrator may want to see how often an API Key is used, or when the last time was. Logging hits to `packages.json`, or when releases are downloaded, and displaying that to admins might be a good extension plugin, if not built-in to SatisPress itself.

**Comment by bradyvercher** [comment]
That's one thing I was thinking would be good for the next release, but it can go in whenever. At the very least, injecting a `Psr\Log\NullLogger` wherever needed would allow the logger service to be replaced in the container.
