### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#7]
I added Hello Dolly to SatisPress (checked the checkbox on the Plugins page), and then later deleted the plugin via FTP. Each row on the Plugins page now shows:

![screenshot 2016-05-25 13 43 41](https://cloud.githubusercontent.com/assets/88371/15540377/e6b81b1c-227e-11e6-874b-928d3f09d743.png)

**Comment by bradyvercher** [comment]
Quick, put it back! 😉 

The quickest way to get rid of those notices is to reinstall Hello Dolly, remove it from the SatisPress index, then delete it again. Or you could remove it from the `satispress_plugins` option, too.

I'll have to spend some time to implement better handling for nonexistent packages.

**Comment by GaryJones** [comment]
As it happens, that's exactly what I did do, but still wanted to report this issue upstream :-)

**Comment by philipnewcomer** [comment]
Experienced this issue as well. Only, I deleted the plugin using the WordPress UI rather than through FTP. It took down our build system completely due to Composer throwing an exception `[UnexpectedValueException] Invalid version string ""` for the plugin I had just deleted.

**Comment by AaronHolbrook** [comment]
Yea, same issue here also

**Comment by bradyvercher** [comment]
I've shifted focus to building a [new plugin we're calling Crate](https://cratewp.com/) that will eventually supersede SatisPress, so don't have much time to spend on this project. If this issue is a major problem for anyone, PRs are happily accepted.

If you've found SatisPress useful, I'm interested in learning how I can help improve Composer support in WordPress and would [appreciate your input](https://goo.gl/forms/5nDTqQuRigexSHT93).

**Comment by AaronHolbrook** [comment]
For future visitors, how I've dealt with correcting this issue when it arises is to go into the database and look for the `satispress_plugins` option.

Copy that, paste it here: https://serializededitor.com and then you can easily remove whatever plugin you were trying to get rid of. Copy the updated serialized data and paste it back into the `satispress_plugins` option.

**Comment by bradyvercher** [comment]
Since this is still causing issues, I tried to implement a quick fix in baaa38a. I'll go ahead and push out a new release, but let me know if that doesn't solve the issue.

**Comment by AaronHolbrook** [comment]
Thanks @bradyvercher !
