### ISSUE TITLE
Repository snippet needs to account for HTTPS

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#8]
The `repositories` snippet on the admin page needs to account for HTTPS. My satispress site uses HTTPS, but the snippet suggests `http://`. Actually trying this, gives a composer error that references https://getcomposer.org/doc/06-config.md#secure-http

**Comment by bradyvercher** [comment]
I'm using this over HTTPS and haven't run into this. That snippet is using `home_url()`, which I believe should already account for the scheme.

**Comment by GaryJones** [comment]
Although HSTS was setting my site to serve over https, my home URL was still http, hence the discrepancy. All good now.
